language: node_js

node_js:
- '0.12'

before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_28b0d322b02e_key -iv $encrypted_28b0d322b02e_iv -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
  # - cat ~/.ssh/id_rsa
  # Set the permission of the key
  - chmod 600 ~/.ssh/id_rsa
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/id_rsa
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name "dellheng"
  - git config --global user.email mrheng@163.com
  # Clone the repository
  - git clone git@github.com:oumind/oumind.git .deploy_git
  - git checkout gh-pages


install:
- npm install hexo-cli -g
- npm install

script:
- hexo generate && hexo deploy

branches:
  only:
  - master
